Links/Websites used during this course:
1. Download notepad ++: https://notepad-plus-plus.org/downloa...
2. class file structure: https://docs.oracle.com/javase/specs/...
3. File to hexa decimal converter: http://tomeko.net/online_tools/file_t...
4. JVM specification: https://docs.oracle.com/javase/specs/...
5. Java Language & JVM Specification: https://docs.oracle.com/javase/specs/
6. Java Language specification: https://docs.oracle.com/javase/specs/...
7. Java18 API specification: https://docs.oracle.com/en/java/javas...
8. Java version history: https://en.wikipedia.org/wiki/Java_ve...
9. Install java/ Download java: https://www.oracle.com/java/technolog...
